-- CPV notes (docs/specs/public-detail-pages.md, slice 3)
--
-- One generated paragraph per official CPV code, Greek and English, next to
-- the exact official name. Generated LOCALLY by cpv_notes.py through the
-- Anthropic Batch API and pushed to production as finished rows; the app only
-- reads this table.
--
-- input_hash covers model + prompt version + the code's context (its names,
-- ancestors and sub-codes), so a prompt change or a renamed code marks exactly
-- the affected rows stale. hidden_at takes a note down without regenerating.
--
-- cpv_note_batch is local bookkeeping (which batches were submitted and
-- collected); production carries it empty.
--
-- No DO $$ blocks: the Supabase dashboard editor splits them.

BEGIN;

CREATE TABLE IF NOT EXISTS proc.cpv_note (
    cpv_code        varchar(10) PRIMARY KEY
                    REFERENCES proc.cpv_code(cpv_code) ON DELETE CASCADE,
    text_el         text        NOT NULL,
    text_en         text        NOT NULL,
    model           text        NOT NULL,
    prompt_version  integer     NOT NULL,
    input_hash      text        NOT NULL,
    input_tokens    integer,
    output_tokens   integer,
    cost_micro_usd  bigint,
    batch_id        text,
    generated_at    timestamptz NOT NULL DEFAULT now(),
    hidden_at       timestamptz,
    hidden_reason   text
);

COMMENT ON TABLE proc.cpv_note IS
  'AI-written el/en paragraph per CPV code (public CPV pages); generated by cpv_notes.py, never by the app.';

CREATE TABLE IF NOT EXISTS proc.cpv_note_batch (
    batch_id        text        PRIMARY KEY,
    model           text        NOT NULL,
    prompt_version  integer     NOT NULL,
    n_requests      integer     NOT NULL,
    submitted_at    timestamptz NOT NULL DEFAULT now(),
    collected_at    timestamptz,
    n_stored        integer,
    n_failed        integer
);

COMMIT;
